[package]
version = "1.1.0"
name = "koerier"
description = "A self-hosted lightning address server for LND"
authors = ["Luis Schwab <dev@luisschwab.net"]
repository = "https://github.com/luisschwab/koerier"
documentation = "https://docs.rs/koerier"
keywords = ["bitcoin", "lightning", "lnd", "webserver"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.85.0" # MSRV

[[bin]]
name = "koerier"
path = "src/koerier.rs"

[dependencies]
axum = "0.8.8"
base64 = "0.22.1"
clap = { version = "4.5.60", features = ["derive"] }
env_logger = "0.11.9"
hex = "0.4.3"
image = "0.25.9"
log = "0.4.29"
rand = "0.10.0"
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "net", "macros"] }
toml = "1.0.3"
# These pins are needed for `Cargo-minimal.toml`:
num-bigint = { version = "0.4.2" }

[package.metadata.rbmt.toolchains]
stable = "1.95.0"
nightly = "nightly-2026-03-18"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.rbmt.lint]
allowed_duplicates = [
    "cpufeatures",
    "getrandom",
    "rand",
    "rand_core",
    "r-efi",
    "windows-sys",
    "wit-bindgen",
    "zune-core",
    "zune-jpeg"
]
