[package]
version = "1.1.0"
name = "koerier"
description = "A self-hosted lightning address server for LND"
authors = ["Luis Schwab <dev@luisschwab.net"]
repository = "https://github.com/luisschwab/koerier"
documentation = "https://docs.rs/koerier"
keywords = ["bitcoin", "lightning", "lnd", "webserver"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.85.0" # MSRV

[[bin]]
name = "koerier"
path = "src/koerier.rs"

[dependencies]
axum = { version = "0.8" }
base64 = { version = "0.22" }
clap = { version = "4.5", features = ["derive"] }
env_logger = { version = "0.11" }
hex = { version = "0.4" }
image = { version = "0.25" }
rand = { version = "0.10.1" }
reqwest = { version = "0.13.3", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149" }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sha2 = { version = "0.11" }
tokio = { version = "1.49.0", features = ["rt-multi-thread", "net", "macros"] }
toml = { version = "1" }
# These pins are needed for `Cargo-minimal.toml`:
num-bigint = { version = "0.4.2" } # blame: image v0.25.0

[package.metadata.rbmt.toolchains]
stable = "1.95.0"
nightly = "nightly-2026-03-18"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.rbmt.lint]
allowed_duplicates = [
    "cpufeatures",
    "getrandom",
    "rand",
    "rand_core",
    "r-efi",
    "windows-sys",
    "wit-bindgen",
    "zune-core",
    "zune-jpeg"
]
